name: bytefight-server
services:
  db:
    image: postgres:16.4
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 10

  pgbackweb:
    image: eduardolat/pgbackweb:latest
    ports:
      - "8085:8085"
    volumes:
      - ./backups:/backups
    environment:
      PBW_ENCRYPTION_KEY: "${PBW_ENCRYPTION_KEY}"
      PBW_POSTGRES_CONN_STRING: "postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable"
    depends_on:
      db:
        condition: service_healthy

  spring:
    build:
      context: ./
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./storage:/app/storage

volumes:
  db_data:
    driver: local
  pgadmin_data:
