name: bytefight-server
services:
  postgres:
    image: postgres:16.4
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c pg_stat_statements.max=10000
      -c pg_stat_statements.track_planning=on
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 10

  spring:
    build:
      context: ./
    depends_on:
      postgres:
        condition: service_healthy
      loki:
        condition: service_started
    env_file:
      - .env
    ports:
      - "${HOST_PORT}:8080"
    volumes:
      - storage:/app/storage
    environment:
      SPRING_PROFILES_ACTIVE: prod

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    depends_on:
      - postgres
    entrypoint: cloudflared
    command:
      - tunnel
      - --no-autoupdate
      - run
      - --token
      - "${CLOUDFLARE_TOKEN}"
    env_file:
      - .env

  grafana:
    image: grafana/grafana:latest
    ports:
      - "${GRAFANA_HOST_PORT}:3000"
    depends_on:
      - postgres
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards:ro
    restart: unless-stopped
    environment:
      GF_SERVER_ROOT_URL: "${GF_SERVER_ROOT_URL}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    command:
      - '--log.level=warn'
    environment:
      DATA_SOURCE_NAME: "postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    depends_on:
      - postgres_exporter

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml

volumes:
  db_data:
    driver: local
  storage:
    driver: local
  grafana_data:
    driver: local
  prometheus_data:
    driver: local