spring:
  application:
    name: BotFightWebServer
  datasource:
    url: jdbc:postgresql://localhost:5432/bytefightdb
    username: bytefight
    password: password
  rabbitmq:
    uri: amqp://guest:guest@localhost:5672

app:
  dev:
    admin-user:
      enabled: true
      email: admin@example.com
      password: password
      username: admin

storage:
  root: ./storage
  hmac-secret: secret

turnstile:
  enabled: false
  site-key: 1x00000000000000000000AA
  secret-key: 2x0000000000000000000000000000000AA

logging:
  file:
    name: logs/application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

hibernate:
  search:
    default:
      directory_provider: filesystem
      indexBase: ./data/index/default

server:
  forward-headers-strategy: framework
