spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    baseline-on-migrate: true
app:
  auth:
    jwt-secret: excyS1grB5eLRbxWl4oomyasIXgBeYlSicEBLOmAtzs
    admin-secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaXNzIjoic3VwYWJhc2UiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiaWF0IjowLCJleHAiOjQwNzA5MzA0MDB9.9YbsIjpvXGnOO3Mrs_V-U3iMiJnLum98P0TLpSgzgek
    base-url: http://localhost:9999
    read-timeout-ms: 5000
    connect-timeout-ms: 3000