CREATE TYPE "tournament_status" AS ENUM (
    'DRAFT',
    'OPEN',
    'IN_PROGRESS',
    'COMPLETE'
);

CREATE TYPE "tournament_entry_status" AS ENUM (
    'ACTIVE',
    'ELIMINATED'
);

CREATE TYPE "tournament_bracket_type" AS ENUM (
    'WINNERS',
    'LOSERS',
    'GRAND_FINAL',
    'GRAND_FINAL_RESET'
);

CREATE TYPE "tournament_match_state" AS ENUM (
    'PENDING',
    'QUEUED',
    'IN_PROGRESS',
    'COMPLETE',
    'SKIPPED'
);

CREATE TABLE "tournament" (
    "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at"  timestamp NOT NULL DEFAULT (now()),
    "updated_at"  timestamp NOT NULL DEFAULT (now()),
    "uuid"        uuid UNIQUE NOT NULL,
    "competition_id" bigint NOT NULL,
    "name"        varchar NOT NULL,
    "status"      tournament_status NOT NULL DEFAULT 'DRAFT',
    "bracket_size" integer,
    "first_place_entry_id"  bigint,
    "second_place_entry_id" bigint,
    "started_at"  timestamp,
    "finished_at" timestamp
);

CREATE TABLE "tournament_entry" (
    "id"            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at"    timestamp NOT NULL DEFAULT (now()),
    "updated_at"    timestamp NOT NULL DEFAULT (now()),
    "tournament_id" bigint NOT NULL,
    "team_id"       bigint NOT NULL,
    "seed"          integer,
    "losses"        integer NOT NULL DEFAULT 0,
    "status"        tournament_entry_status NOT NULL DEFAULT 'ACTIVE',
    "eliminated_at" timestamp,
    CONSTRAINT tournament_entry_tournament_team_unique UNIQUE (tournament_id, team_id)
);

CREATE TABLE "tournament_match" (
    "id"                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at"            timestamp NOT NULL DEFAULT (now()),
    "updated_at"            timestamp NOT NULL DEFAULT (now()),
    "uuid"                  uuid UNIQUE NOT NULL,
    "tournament_id"         bigint NOT NULL,
    "bracket_type"          tournament_bracket_type,
    "round_number"          integer,
    "match_index"           integer,
    "team_one_entry_id"     bigint,
    "team_two_entry_id"     bigint,
    "state"                 tournament_match_state NOT NULL DEFAULT 'PENDING',
    "series_length"         integer,
    "team_one_series_wins"  integer NOT NULL DEFAULT 0,
    "team_two_series_wins"  integer NOT NULL DEFAULT 0,
    "winner_entry_id"       bigint,
    "loser_entry_id"        bigint,
    "next_winner_match_id"  bigint,
    "next_winner_slot"      integer,
    "next_loser_match_id"   bigint,
    "next_loser_slot"       integer
);

CREATE TABLE "tournament_game" (
    "id"                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at"          timestamp NOT NULL DEFAULT (now()),
    "updated_at"          timestamp NOT NULL DEFAULT (now()),
    "tournament_match_id" bigint NOT NULL,
    "game_match_id"       bigint UNIQUE NOT NULL,
    "game_number"         integer NOT NULL,
    "result_processed"    boolean NOT NULL DEFAULT false,
    CONSTRAINT tournament_game_match_game_number_unique UNIQUE (tournament_match_id, game_number)
);

ALTER TABLE "tournament"
    ADD CONSTRAINT tournament_competition_id_fkey
        FOREIGN KEY (competition_id) REFERENCES competitions (id);

ALTER TABLE "tournament"
    ADD CONSTRAINT tournament_first_place_entry_id_fkey
        FOREIGN KEY (first_place_entry_id) REFERENCES tournament_entry (id);

ALTER TABLE "tournament"
    ADD CONSTRAINT tournament_second_place_entry_id_fkey
        FOREIGN KEY (second_place_entry_id) REFERENCES tournament_entry (id);

ALTER TABLE "tournament_entry"
    ADD CONSTRAINT tournament_entry_tournament_id_fkey
        FOREIGN KEY (tournament_id) REFERENCES tournament (id);

ALTER TABLE "tournament_entry"
    ADD CONSTRAINT tournament_entry_team_id_fkey
        FOREIGN KEY (team_id) REFERENCES teams (id);

ALTER TABLE "tournament_match"
    ADD CONSTRAINT tournament_match_tournament_id_fkey
        FOREIGN KEY (tournament_id) REFERENCES tournament (id);

ALTER TABLE "tournament_match"
    ADD CONSTRAINT tournament_match_team_one_entry_id_fkey
        FOREIGN KEY (team_one_entry_id) REFERENCES tournament_entry (id);

ALTER TABLE "tournament_match"
    ADD CONSTRAINT tournament_match_team_two_entry_id_fkey
        FOREIGN KEY (team_two_entry_id) REFERENCES tournament_entry (id);

ALTER TABLE "tournament_match"
    ADD CONSTRAINT tournament_match_winner_entry_id_fkey
        FOREIGN KEY (winner_entry_id) REFERENCES tournament_entry (id);

ALTER TABLE "tournament_match"
    ADD CONSTRAINT tournament_match_loser_entry_id_fkey
        FOREIGN KEY (loser_entry_id) REFERENCES tournament_entry (id);

ALTER TABLE "tournament_game"
    ADD CONSTRAINT tournament_game_tournament_match_id_fkey
        FOREIGN KEY (tournament_match_id) REFERENCES tournament_match (id);

ALTER TABLE "tournament_game"
    ADD CONSTRAINT tournament_game_game_match_id_fkey
        FOREIGN KEY (game_match_id) REFERENCES game_matches (id);
