-- This script was generated by the Schema Diff utility in pgAdmin 4.
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.
BEGIN;
ALTER TABLE IF EXISTS public.users
    ADD COLUMN resume_file bigint;
ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_resume_file_key UNIQUE (resume_file);
ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_resume_file_fkey FOREIGN KEY (resume_file)
        REFERENCES public.file_records (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;

END;