-- This script was generated by the Schema Diff utility in pgAdmin 4. 
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated 
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps. 
BEGIN;
ALTER TABLE IF EXISTS public.teams DROP COLUMN IF EXISTS is_deleted;
ALTER TABLE IF EXISTS public.file_records DROP COLUMN IF EXISTS is_deleted;
ALTER TABLE IF EXISTS public.submissions DROP COLUMN IF EXISTS is_deleted;
COMMENT ON COLUMN public.tournament.uuid
    IS 'Public identifier for the tournament';
ALTER TABLE IF EXISTS public.tournament DROP CONSTRAINT IF EXISTS tournament_competition_id_fkey;

ALTER TABLE IF EXISTS public.tournament DROP CONSTRAINT IF EXISTS tournament_first_place_entry_id_fkey;

ALTER TABLE IF EXISTS public.tournament DROP CONSTRAINT IF EXISTS tournament_second_place_entry_id_fkey;

ALTER TABLE IF EXISTS public.tournament
    ADD CONSTRAINT tournament_competition_id_fkey FOREIGN KEY (competition_id)
    REFERENCES public.competitions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    DEFERRABLE;

ALTER TABLE IF EXISTS public.tournament
    ADD CONSTRAINT tournament_first_place_entry_id_fkey FOREIGN KEY (first_place_entry_id)
    REFERENCES public.tournament_entry (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    DEFERRABLE;

ALTER TABLE IF EXISTS public.tournament
    ADD CONSTRAINT tournament_second_place_entry_id_fkey FOREIGN KEY (second_place_entry_id)
    REFERENCES public.tournament_entry (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    DEFERRABLE;
COMMENT ON COLUMN public.tournament_game.game_number
    IS '1-based game number within the series';

COMMENT ON COLUMN public.tournament_game.result_processed
    IS 'prevents duplicate result handling';
ALTER TABLE IF EXISTS public.tournament_game DROP CONSTRAINT IF EXISTS tournament_game_game_match_id_key;

ALTER TABLE IF EXISTS public.tournament_game DROP CONSTRAINT IF EXISTS tournament_game_match_game_number_unique;
ALTER TABLE IF EXISTS public.tournament_game DROP CONSTRAINT IF EXISTS tournament_game_game_match_id_fkey;

ALTER TABLE IF EXISTS public.tournament_game DROP CONSTRAINT IF EXISTS tournament_game_tournament_match_id_fkey;

ALTER TABLE IF EXISTS public.tournament_game
    ADD CONSTRAINT tournament_game_game_match_id_fkey FOREIGN KEY (game_match_id)
    REFERENCES public.game_matches (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    DEFERRABLE;

ALTER TABLE IF EXISTS public.tournament_game
    ADD CONSTRAINT tournament_game_tournament_match_id_fkey FOREIGN KEY (tournament_match_id)
    REFERENCES public.tournament_match (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    DEFERRABLE;
CREATE UNIQUE INDEX IF NOT EXISTS tournament_game_tournament_match_id_game_number_idx
    ON public.tournament_game USING btree
    (tournament_match_id ASC NULLS LAST, game_number ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;


DROP INDEX IF EXISTS public.game_match_files_null_team_unique;
ALTER TABLE IF EXISTS public.tournament_entry
ALTER COLUMN seed SET NOT NULL;

COMMENT ON COLUMN public.tournament_entry.seed
    IS '1-based seed assigned at enrollment';
ALTER TABLE IF EXISTS public.tournament_entry DROP CONSTRAINT IF EXISTS tournament_entry_tournament_team_unique;
ALTER TABLE IF EXISTS public.tournament_entry DROP CONSTRAINT IF EXISTS tournament_entry_team_id_fkey;

ALTER TABLE IF EXISTS public.tournament_entry DROP CONSTRAINT IF EXISTS tournament_entry_tournament_id_fkey;

ALTER TABLE IF EXISTS public.tournament_entry
    ADD CONSTRAINT tournament_entry_team_id_fkey FOREIGN KEY (team_id)
    REFERENCES public.teams (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    DEFERRABLE;

ALTER TABLE IF EXISTS public.tournament_entry
    ADD CONSTRAINT tournament_entry_tournament_id_fkey FOREIGN KEY (tournament_id)
    REFERENCES public.tournament (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    DEFERRABLE;
CREATE UNIQUE INDEX IF NOT EXISTS tournament_entry_tournament_id_team_id_idx
    ON public.tournament_entry USING btree
    (tournament_id ASC NULLS LAST, team_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tournament_match
ALTER COLUMN bracket_type SET NOT NULL;

ALTER TABLE IF EXISTS public.tournament_match
ALTER COLUMN match_index SET NOT NULL;

COMMENT ON COLUMN public.tournament_match.match_index
    IS '1-based index within the round';

COMMENT ON COLUMN public.tournament_match.next_loser_slot
    IS '1 = team_one_entry, 2 = team_two_entry';

COMMENT ON COLUMN public.tournament_match.next_winner_slot
    IS '1 = team_one_entry, 2 = team_two_entry';

ALTER TABLE IF EXISTS public.tournament_match
ALTER COLUMN round_number SET NOT NULL;

ALTER TABLE IF EXISTS public.tournament_match
ALTER COLUMN series_length SET NOT NULL;

COMMENT ON COLUMN public.tournament_match.series_length
    IS '5 for normal matches, 7 for grand finals';
ALTER TABLE IF EXISTS public.tournament_match DROP CONSTRAINT IF EXISTS tournament_match_loser_entry_id_fkey;

ALTER TABLE IF EXISTS public.tournament_match DROP CONSTRAINT IF EXISTS tournament_match_team_one_entry_id_fkey;

ALTER TABLE IF EXISTS public.tournament_match DROP CONSTRAINT IF EXISTS tournament_match_team_two_entry_id_fkey;

ALTER TABLE IF EXISTS public.tournament_match DROP CONSTRAINT IF EXISTS tournament_match_tournament_id_fkey;

ALTER TABLE IF EXISTS public.tournament_match DROP CONSTRAINT IF EXISTS tournament_match_winner_entry_id_fkey;

ALTER TABLE IF EXISTS public.tournament_match
    ADD CONSTRAINT tournament_match_loser_entry_id_fkey FOREIGN KEY (loser_entry_id)
    REFERENCES public.tournament_entry (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    DEFERRABLE;

ALTER TABLE IF EXISTS public.tournament_match
    ADD CONSTRAINT tournament_match_next_loser_match_id_fkey FOREIGN KEY (next_loser_match_id)
    REFERENCES public.tournament_match (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    DEFERRABLE;

ALTER TABLE IF EXISTS public.tournament_match
    ADD CONSTRAINT tournament_match_next_winner_match_id_fkey FOREIGN KEY (next_winner_match_id)
    REFERENCES public.tournament_match (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    DEFERRABLE;

ALTER TABLE IF EXISTS public.tournament_match
    ADD CONSTRAINT tournament_match_team_one_entry_id_fkey FOREIGN KEY (team_one_entry_id)
    REFERENCES public.tournament_entry (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    DEFERRABLE;

ALTER TABLE IF EXISTS public.tournament_match
    ADD CONSTRAINT tournament_match_team_two_entry_id_fkey FOREIGN KEY (team_two_entry_id)
    REFERENCES public.tournament_entry (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    DEFERRABLE;

ALTER TABLE IF EXISTS public.tournament_match
    ADD CONSTRAINT tournament_match_tournament_id_fkey FOREIGN KEY (tournament_id)
    REFERENCES public.tournament (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    DEFERRABLE;

ALTER TABLE IF EXISTS public.tournament_match
    ADD CONSTRAINT tournament_match_winner_entry_id_fkey FOREIGN KEY (winner_entry_id)
    REFERENCES public.tournament_entry (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    DEFERRABLE;

END;