CREATE TABLE "profile" (
   "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   "created_at" timestamp NOT NULL DEFAULT (now()),
   "updated_at" timestamp NOT NULL DEFAULT (now()),
   "player_id" bigint NOT NULL,
   "description" varchar(512),
   "major" varchar(256) NOT NULL,
   "year" integer NOT NULL,
   "is_deleted" boolean NOT NULL DEFAULT false,
   "deleted_at" timestamp
);

CREATE UNIQUE INDEX ON "profile" ("player_id")
    WHERE "is_deleted" = false;

ALTER TABLE "profile"
    ADD CONSTRAINT profile_player_id_fkey
        FOREIGN KEY ("player_id") REFERENCES "players" ("id");