ALTER TABLE players
    ADD COLUMN description varchar(512),
    ADD COLUMN major varchar(256),
    ADD COLUMN graduation_year integer,
    ADD COLUMN profile_visibility varchar(32) NOT NULL DEFAULT 'PRIVATE',
    ADD COLUMN full_name varchar(100),
    ADD COLUMN school varchar(150),
    ADD COLUMN avatar_file bigint,
    ADD CONSTRAINT players_graduation_year_nonnegative
        CHECK (graduation_year IS NULL OR graduation_year >= 0),
    ADD CONSTRAINT players_profile_visibility_valid
        CHECK (profile_visibility IN ('PUBLIC', 'TEAM_MEMBERS', 'PRIVATE'));

UPDATE players AS player
SET description = social.description,
    major = social.major,
    graduation_year = social.year,
    profile_visibility = 'PUBLIC'
    FROM profile AS social
WHERE social.player_id = player.id
    AND social.is_deleted = false;

CREATE TABLE player_social_links (
     id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     created_at timestamp NOT NULL DEFAULT now(),
     updated_at timestamp NOT NULL DEFAULT now(),
     player_id bigint NOT NULL,
     platform varchar(30) NOT NULL,
     url varchar(500) NOT NULL,

     CONSTRAINT player_social_links_player_fkey
         FOREIGN KEY (player_id) REFERENCES players(id)
             ON DELETE CASCADE,

     CONSTRAINT player_social_links_platform_valid
         CHECK (platform IN ('GITHUB', 'LINKEDIN', 'DISCORD')),

     CONSTRAINT player_social_links_player_platform_unique
         UNIQUE (player_id, platform)
);

ALTER TABLE players
    ADD CONSTRAINT players_avatar_file_unique UNIQUE (avatar_file),
    ADD CONSTRAINT players_avatar_file_fkey
        FOREIGN KEY (avatar_file) REFERENCES file_records(id);

DROP TABLE profile;