-- Server-side scrim endpoint (#160): a new unrated match reason and the atomic
-- volume-budget table that also serves as the scrim audit/telemetry record.

-- New match reason. ADD VALUE is allowed inside a migration transaction on
-- PostgreSQL 12+ as long as the value is not *used* in the same transaction
-- (it isn't here). IF NOT EXISTS keeps re-runs and merges idempotent.
ALTER TYPE "match_reason" ADD VALUE IF NOT EXISTS 'scrim';

CREATE TABLE "scrim_usage" (
    "id"           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at"   timestamp NOT NULL DEFAULT (now()),
    "team_id"      bigint NOT NULL,
    "window_kind"  text NOT NULL,
    "window_start" timestamptz NOT NULL,
    "count"        integer NOT NULL DEFAULT 0,
    CONSTRAINT "uk_scrim_usage_team_window"
        UNIQUE ("team_id", "window_kind", "window_start")
);

ALTER TABLE "scrim_usage" ADD FOREIGN KEY ("team_id") REFERENCES "teams" ("id");

CREATE INDEX "idx_scrim_usage_team" ON "scrim_usage" ("team_id");
