CREATE TYPE "match_status" AS ENUM (
    'created',
    'scheduling',
    'waiting',
    'in_progress',
    'failed',
    'team_a_win',
    'team_b_win',
    'draw'
    );

CREATE TYPE "match_reason" AS ENUM (
    'validation',
    'scrimmage',
    'ladder',
    'tournament',
    'other'
    );

CREATE TYPE "submission_validity" AS ENUM (
    'valid',
    'invalid',
    'not_evaluated'
    );

CREATE TYPE "team_type" AS ENUM (
    'regular',
    'ta_bot'
    );

CREATE TABLE "file_records" (
                                "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "created_at" timestamp NOT NULL DEFAULT (now()),
                                "updated_at" timestamp NOT NULL DEFAULT (now()),
                                "uuid" uuid UNIQUE NOT NULL,
                                "filename" varchar NOT NULL,
                                "content_type" varchar(255) NOT NULL,
                                "size" bigint NOT NULL,
                                "sha256" varchar NOT NULL,
                                "storage_path" varchar NOT NULL
);

CREATE TABLE "users" (
                         "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "created_at" timestamp NOT NULL DEFAULT (now()),
                         "updated_at" timestamp NOT NULL DEFAULT (now()),
                         "uuid" uuid UNIQUE NOT NULL,
                         "email" varchar(255) UNIQUE NOT NULL,
                         "is_admin" boolean NOT NULL DEFAULT false
);

CREATE TABLE "players" (
                           "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "created_at" timestamp NOT NULL DEFAULT (now()),
                           "updated_at" timestamp NOT NULL DEFAULT (now()),
                           "user_id" bigint UNIQUE NOT NULL,
                           "username" varchar(50) UNIQUE NOT NULL,
                           "username_normalized" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "competitions" (
                                "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "created_at" timestamp NOT NULL DEFAULT (now()),
                                "updated_at" timestamp NOT NULL DEFAULT (now()),
                                "slug" varchar(255) UNIQUE NOT NULL,
                                "name" varchar NOT NULL,
                                "description" varchar,
                                "is_active" boolean NOT NULL DEFAULT false,
                                "is_whitelisted" boolean NOT NULL DEFAULT false,
                                "max_players_per_team" integer NOT NULL
);

CREATE TABLE "whitelist_entries" (
                                     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     "created_at" timestamp NOT NULL DEFAULT (now()),
                                     "updated_at" timestamp NOT NULL DEFAULT (now()),
                                     "competition_id" bigint NOT NULL,
                                     "email" varchar(255)
);

CREATE TABLE "teams" (
                         "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "created_at" timestamp NOT NULL DEFAULT (now()),
                         "updated_at" timestamp NOT NULL DEFAULT (now()),
                         "competition_id" bigint NOT NULL,
                         "uuid" uuid UNIQUE NOT NULL DEFAULT (gen_random_uuid()),
                         "name" varchar(50) NOT NULL,
                         "name_normalized" varchar(50) NOT NULL,
                         "quote" varchar,
                         "join_code" varchar(50) UNIQUE,
                         "display_members" boolean NOT NULL,
                         "active_submission_id" bigint,
                         "type" team_type NOT NULL DEFAULT 'regular',
                         "is_deleted" boolean NOT NULL DEFAULT false,
                         "deleted_at" timestamp,
                         "created_by_user_id" bigint,
                         "updated_by_user_id" bigint
);

CREATE TABLE "team_stats" (
                              "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              "created_at" timestamp NOT NULL DEFAULT (now()),
                              "updated_at" timestamp NOT NULL DEFAULT (now()),
                              "team_id" bigint NOT NULL,
                              "ladder" varchar(50) NOT NULL,
                              "matches_played" integer NOT NULL DEFAULT 0,
                              "wins" integer NOT NULL DEFAULT 0,
                              "losses" integer NOT NULL DEFAULT 0,
                              "draws" integer NOT NULL DEFAULT 0,
                              "glicko_rating" numeric(7,2) NOT NULL,
                              "glicko_rd" double precision NOT NULL,
                              "glicko_volatility" double precision NOT NULL
);

CREATE TABLE "team_members" (
                                "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "created_at" timestamp NOT NULL DEFAULT (now()),
                                "updated_at" timestamp NOT NULL DEFAULT (now()),
                                "player_id" bigint NOT NULL,
                                "team_id" bigint NOT NULL,
                                "competition_id" bigint NOT NULL
);

CREATE TABLE "team_glicko_history" (
                                       "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       "created_at" timestamp NOT NULL DEFAULT (now()),
                                       "updated_at" timestamp NOT NULL DEFAULT (now()),
                                       "team_id" bigint NOT NULL,
                                       "ladder" varchar(50) NOT NULL,
                                       "game_match_id" bigint,
                                       "old_glicko" numeric(7,2) NOT NULL,
                                       "new_glicko" numeric(7,2) NOT NULL
);

CREATE TABLE "submissions" (
                               "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               "created_at" timestamp NOT NULL DEFAULT (now()),
                               "updated_at" timestamp NOT NULL DEFAULT (now()),
                               "uuid" uuid NOT NULL,
                               "file_record_id" bigint NOT NULL,
                               "team_id" bigint NOT NULL,
                               "description" varchar(512),
                               "validity" submission_validity NOT NULL DEFAULT 'not_evaluated',
                               "is_deleted" boolean NOT NULL DEFAULT false,
                               "deleted_at" timestamp,
                               "created_by_user_id" bigint,
                               "updated_by_user_id" bigint
);

CREATE TABLE "game_matches" (
                                "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "created_at" timestamp NOT NULL DEFAULT (now()),
                                "updated_at" timestamp NOT NULL DEFAULT (now()),
                                "uuid" uuid NOT NULL DEFAULT (gen_random_uuid()),
                                "competition_id" bigint NOT NULL,
                                "ladder" varchar(50) NOT NULL,
                                "team_a_id" bigint NOT NULL,
                                "team_b_id" bigint NOT NULL,
                                "submission_a_id" bigint NOT NULL,
                                "submission_b_id" bigint NOT NULL,
                                "match_settings" jsonb NOT NULL,
                                "status" match_status NOT NULL DEFAULT 'scheduling',
                                "reason" match_reason NOT NULL DEFAULT 'other',
                                "matchmaking_event_id" bigint,
                                "scheduled_at" timestamp,
                                "started_at" timestamp,
                                "finished_at" timestamp,
                                "created_by_user_id" bigint,
                                "updated_by_user_id" bigint
);

CREATE TABLE "game_match_files" (
                                    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    "created_at" timestamp NOT NULL DEFAULT (now()),
                                    "updated_at" timestamp NOT NULL DEFAULT (now()),
                                    "game_match_id" bigint NOT NULL,
                                    "uuid" uuid NOT NULL,
                                    "slug" varchar(50) NOT NULL,
                                    "file_record_id" bigint NOT NULL,
                                    "team_id" bigint
);

CREATE TABLE "matchmaking_events" (
                                      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      "created_at" timestamp NOT NULL DEFAULT (now()),
                                      "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE UNIQUE INDEX ON "teams" ("competition_id", "name_normalized");

CREATE UNIQUE INDEX ON "team_stats" ("team_id", "ladder");

CREATE UNIQUE INDEX ON "team_members" ("team_id", "player_id");

CREATE UNIQUE INDEX ON "team_members" ("competition_id", "player_id");

CREATE INDEX ON "team_glicko_history" ("team_id", "game_match_id");

CREATE UNIQUE INDEX ON "game_match_files" ("game_match_id", "slug", "team_id");

COMMENT ON COLUMN "users"."uuid" IS 'corresponds with supabase user UUID';

ALTER TABLE "players" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "whitelist_entries" ADD FOREIGN KEY ("competition_id") REFERENCES "competitions" ("id");

ALTER TABLE "teams" ADD FOREIGN KEY ("competition_id") REFERENCES "competitions" ("id");

ALTER TABLE "teams" ADD FOREIGN KEY ("active_submission_id") REFERENCES "submissions" ("id");

ALTER TABLE "team_stats" ADD FOREIGN KEY ("team_id") REFERENCES "teams" ("id");

ALTER TABLE "team_members" ADD FOREIGN KEY ("player_id") REFERENCES "players" ("id");

ALTER TABLE "team_members" ADD FOREIGN KEY ("team_id") REFERENCES "teams" ("id");

ALTER TABLE "team_members" ADD FOREIGN KEY ("competition_id") REFERENCES "competitions" ("id");

ALTER TABLE "team_glicko_history" ADD FOREIGN KEY ("team_id") REFERENCES "teams" ("id");

ALTER TABLE "team_glicko_history" ADD FOREIGN KEY ("game_match_id") REFERENCES "game_matches" ("id");

ALTER TABLE "submissions" ADD FOREIGN KEY ("file_record_id") REFERENCES "file_records" ("id");

ALTER TABLE "submissions" ADD FOREIGN KEY ("team_id") REFERENCES "teams" ("id");

ALTER TABLE "game_matches" ADD FOREIGN KEY ("competition_id") REFERENCES "competitions" ("id");

ALTER TABLE "game_matches" ADD FOREIGN KEY ("team_a_id") REFERENCES "teams" ("id");

ALTER TABLE "game_matches" ADD FOREIGN KEY ("team_b_id") REFERENCES "teams" ("id");

ALTER TABLE "game_matches" ADD FOREIGN KEY ("submission_a_id") REFERENCES "submissions" ("id");

ALTER TABLE "game_matches" ADD FOREIGN KEY ("submission_b_id") REFERENCES "submissions" ("id");

ALTER TABLE "game_matches" ADD FOREIGN KEY ("matchmaking_event_id") REFERENCES "matchmaking_events" ("id");

ALTER TABLE "game_match_files" ADD FOREIGN KEY ("game_match_id") REFERENCES "game_matches" ("id");

ALTER TABLE "game_match_files" ADD FOREIGN KEY ("file_record_id") REFERENCES "file_records" ("id");

ALTER TABLE "game_match_files" ADD FOREIGN KEY ("team_id") REFERENCES "teams" ("id");

ALTER TABLE "teams" ADD FOREIGN KEY ("created_by_user_id") REFERENCES "users" ("id");

ALTER TABLE "teams" ADD FOREIGN KEY ("updated_by_user_id") REFERENCES "users" ("id");

ALTER TABLE "submissions" ADD FOREIGN KEY ("created_by_user_id") REFERENCES "users" ("id");

ALTER TABLE "submissions" ADD FOREIGN KEY ("updated_by_user_id") REFERENCES "users" ("id");

ALTER TABLE "game_matches" ADD FOREIGN KEY ("created_by_user_id") REFERENCES "users" ("id");

ALTER TABLE "game_matches" ADD FOREIGN KEY ("updated_by_user_id") REFERENCES "users" ("id");