BEGIN;

CREATE TABLE game_match_outcome_reasons (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    competition_id bigint NOT NULL REFERENCES competitions (id) ON DELETE CASCADE,
    code varchar(100) NOT NULL,
    display_label varchar(255) NOT NULL,
    visible boolean NOT NULL DEFAULT true,
    CONSTRAINT game_match_outcome_reasons_competition_code_key UNIQUE (competition_id, code)
);

CREATE INDEX game_match_outcome_reasons_competition_visible_idx
    ON game_match_outcome_reasons (competition_id, visible);

INSERT INTO game_match_outcome_reasons
    (created_at, updated_at, competition_id, code, display_label, visible)
SELECT CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, id, 'timeout', 'Timeout', true
FROM competitions
UNION ALL
SELECT CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, id, 'code_error', 'Code error', true
FROM competitions
ON CONFLICT (competition_id, code) DO NOTHING;

END;
