BEGIN;

CREATE TABLE public.profile_stats (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp NOT NULL DEFAULT (now()),
    "updated_at" timestamp NOT NULL DEFAULT (now()),
    "player_id" bigint NOT NULL,
    "games_played" integer NOT NULL DEFAULT 0,
    "games_played_percentile" double precision
);

ALTER TABLE "profile_stats" ADD FOREIGN KEY ("player_id") REFERENCES "players" ("id");

CREATE UNIQUE INDEX uk_profile_stats_player ON public.profile_stats ("player_id");

END;
