CREATE TABLE "global_stats" (
    "id"         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp NOT NULL DEFAULT (now()),
    "updated_at" timestamp NOT NULL DEFAULT (now()),
    "metric"     varchar   UNIQUE NOT NULL,
    "value"      bigint    NOT NULL
);
