CREATE TYPE "notification_priority" AS ENUM ('NORMAL', 'URGENT');

CREATE TABLE "notifications" (
    "id"                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at"         timestamp NOT NULL DEFAULT (now()),
    "updated_at"         timestamp NOT NULL DEFAULT (now()),
    "created_by_user_id" bigint REFERENCES "users" ("id"),
    "updated_by_user_id" bigint REFERENCES "users" ("id"),
    "priority"           notification_priority NOT NULL DEFAULT 'NORMAL',
    "with_email"         boolean NOT NULL DEFAULT false,
    "title"              varchar(200) NOT NULL,
    "body"               text NOT NULL,
    "competition_id"     bigint NULL REFERENCES "competitions" ("id") ON DELETE CASCADE,
    "expire_at"          timestamp NULL
);

CREATE INDEX "idx_notifications_competition_created"
    ON "notifications" ("competition_id", "created_at" DESC);

ALTER TABLE "users"
    ADD COLUMN "last_notifications_checked" timestamp NOT NULL DEFAULT (now());
