-- This script was generated by the Schema Diff utility in pgAdmin 4.
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.
BEGIN;
ALTER TABLE IF EXISTS public.whitelist_entries DROP CONSTRAINT IF EXISTS whitelist_entries_competition_id_fkey;

ALTER TABLE IF EXISTS public.whitelist_entries
    ADD CONSTRAINT whitelist_entries_competition_id_fkey FOREIGN KEY (competition_id)
        REFERENCES public.competitions (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;
ALTER TABLE IF EXISTS public.teams DROP CONSTRAINT IF EXISTS teams_active_submission_id_fkey;

ALTER TABLE IF EXISTS public.teams DROP CONSTRAINT IF EXISTS teams_competition_id_fkey;

ALTER TABLE IF EXISTS public.teams DROP CONSTRAINT IF EXISTS teams_created_by_user_id_fkey;

ALTER TABLE IF EXISTS public.teams DROP CONSTRAINT IF EXISTS teams_updated_by_user_id_fkey;

ALTER TABLE IF EXISTS public.teams
    ADD CONSTRAINT teams_active_submission_id_fkey FOREIGN KEY (active_submission_id)
        REFERENCES public.submissions (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;

ALTER TABLE IF EXISTS public.teams
    ADD CONSTRAINT teams_competition_id_fkey FOREIGN KEY (competition_id)
        REFERENCES public.competitions (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;

ALTER TABLE IF EXISTS public.teams
    ADD CONSTRAINT teams_created_by_user_id_fkey FOREIGN KEY (created_by_user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;

ALTER TABLE IF EXISTS public.teams
    ADD CONSTRAINT teams_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;
ALTER TABLE IF EXISTS public.team_members DROP CONSTRAINT IF EXISTS team_members_competition_id_fkey;

ALTER TABLE IF EXISTS public.team_members DROP CONSTRAINT IF EXISTS team_members_player_id_fkey;

ALTER TABLE IF EXISTS public.team_members DROP CONSTRAINT IF EXISTS team_members_team_id_fkey;

ALTER TABLE IF EXISTS public.team_members
    ADD CONSTRAINT team_members_competition_id_fkey FOREIGN KEY (competition_id)
        REFERENCES public.competitions (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;

ALTER TABLE IF EXISTS public.team_members
    ADD CONSTRAINT team_members_player_id_fkey FOREIGN KEY (player_id)
        REFERENCES public.players (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;

ALTER TABLE IF EXISTS public.team_members
    ADD CONSTRAINT team_members_team_id_fkey FOREIGN KEY (team_id)
        REFERENCES public.teams (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;
ALTER TABLE IF EXISTS public.submissions DROP CONSTRAINT IF EXISTS submissions_created_by_user_id_fkey;

ALTER TABLE IF EXISTS public.submissions DROP CONSTRAINT IF EXISTS submissions_file_record_id_fkey;

ALTER TABLE IF EXISTS public.submissions DROP CONSTRAINT IF EXISTS submissions_team_id_fkey;

ALTER TABLE IF EXISTS public.submissions DROP CONSTRAINT IF EXISTS submissions_updated_by_user_id_fkey;

ALTER TABLE IF EXISTS public.submissions
    ADD CONSTRAINT submissions_created_by_user_id_fkey FOREIGN KEY (created_by_user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;

ALTER TABLE IF EXISTS public.submissions
    ADD CONSTRAINT submissions_file_record_id_fkey FOREIGN KEY (file_record_id)
        REFERENCES public.file_records (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;

ALTER TABLE IF EXISTS public.submissions
    ADD CONSTRAINT submissions_team_id_fkey FOREIGN KEY (team_id)
        REFERENCES public.teams (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;

ALTER TABLE IF EXISTS public.submissions
    ADD CONSTRAINT submissions_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;
ALTER TABLE IF EXISTS public.ladders DROP COLUMN IF EXISTS matchmaking_interval_seconds;

ALTER TABLE IF EXISTS public.ladders
    ADD COLUMN scheduled_matchmaking_cron text COLLATE pg_catalog."default";
ALTER TABLE IF EXISTS public.ladders DROP CONSTRAINT IF EXISTS ladders_competition_id_fkey;

ALTER TABLE IF EXISTS public.ladders
    ADD CONSTRAINT ladders_competition_id_fkey FOREIGN KEY (competition_id)
        REFERENCES public.competitions (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;
ALTER TABLE IF EXISTS public.game_match_files DROP CONSTRAINT IF EXISTS game_match_files_file_record_id_fkey;

ALTER TABLE IF EXISTS public.game_match_files DROP CONSTRAINT IF EXISTS game_match_files_game_match_id_fkey;

ALTER TABLE IF EXISTS public.game_match_files DROP CONSTRAINT IF EXISTS game_match_files_team_id_fkey;

ALTER TABLE IF EXISTS public.game_match_files
    ADD CONSTRAINT game_match_files_file_record_id_fkey FOREIGN KEY (file_record_id)
        REFERENCES public.file_records (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;

ALTER TABLE IF EXISTS public.game_match_files
    ADD CONSTRAINT game_match_files_game_match_id_fkey FOREIGN KEY (game_match_id)
        REFERENCES public.game_matches (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;

ALTER TABLE IF EXISTS public.game_match_files
    ADD CONSTRAINT game_match_files_team_id_fkey FOREIGN KEY (team_id)
        REFERENCES public.teams (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;
ALTER TABLE IF EXISTS public.game_matches DROP CONSTRAINT IF EXISTS game_matches_competition_id_fkey;

ALTER TABLE IF EXISTS public.game_matches DROP CONSTRAINT IF EXISTS game_matches_competition_id_ladder_fkey;

ALTER TABLE IF EXISTS public.game_matches DROP CONSTRAINT IF EXISTS game_matches_created_by_user_id_fkey;

ALTER TABLE IF EXISTS public.game_matches DROP CONSTRAINT IF EXISTS game_matches_matchmaking_event_id_fkey;

ALTER TABLE IF EXISTS public.game_matches DROP CONSTRAINT IF EXISTS game_matches_submission_a_id_fkey;

ALTER TABLE IF EXISTS public.game_matches DROP CONSTRAINT IF EXISTS game_matches_submission_b_id_fkey;

ALTER TABLE IF EXISTS public.game_matches DROP CONSTRAINT IF EXISTS game_matches_team_a_id_fkey;

ALTER TABLE IF EXISTS public.game_matches DROP CONSTRAINT IF EXISTS game_matches_team_b_id_fkey;

ALTER TABLE IF EXISTS public.game_matches DROP CONSTRAINT IF EXISTS game_matches_updated_by_user_id_fkey;

ALTER TABLE IF EXISTS public.game_matches
    ADD CONSTRAINT game_matches_competition_id_fkey FOREIGN KEY (competition_id)
        REFERENCES public.competitions (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;

ALTER TABLE IF EXISTS public.game_matches
    ADD CONSTRAINT game_matches_competition_id_ladder_fkey FOREIGN KEY (competition_id, ladder)
        REFERENCES public.ladders (competition_id, ladder) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;

ALTER TABLE IF EXISTS public.game_matches
    ADD CONSTRAINT game_matches_created_by_user_id_fkey FOREIGN KEY (created_by_user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;

ALTER TABLE IF EXISTS public.game_matches
    ADD CONSTRAINT game_matches_matchmaking_event_id_fkey FOREIGN KEY (matchmaking_event_id)
        REFERENCES public.matchmaking_events (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;

ALTER TABLE IF EXISTS public.game_matches
    ADD CONSTRAINT game_matches_submission_a_id_fkey FOREIGN KEY (submission_a_id)
        REFERENCES public.submissions (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;

ALTER TABLE IF EXISTS public.game_matches
    ADD CONSTRAINT game_matches_submission_b_id_fkey FOREIGN KEY (submission_b_id)
        REFERENCES public.submissions (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;

ALTER TABLE IF EXISTS public.game_matches
    ADD CONSTRAINT game_matches_team_a_id_fkey FOREIGN KEY (team_a_id)
        REFERENCES public.teams (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;

ALTER TABLE IF EXISTS public.game_matches
    ADD CONSTRAINT game_matches_team_b_id_fkey FOREIGN KEY (team_b_id)
        REFERENCES public.teams (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;

ALTER TABLE IF EXISTS public.game_matches
    ADD CONSTRAINT game_matches_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;
ALTER TABLE IF EXISTS public.players DROP CONSTRAINT IF EXISTS players_user_id_fkey;

ALTER TABLE IF EXISTS public.players
    ADD CONSTRAINT players_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;
ALTER TABLE IF EXISTS public.matchmaking_events DROP CONSTRAINT IF EXISTS matchmaking_events_competition_id_fkey;

ALTER TABLE IF EXISTS public.matchmaking_events
    ADD CONSTRAINT matchmaking_events_competition_id_fkey FOREIGN KEY (competition_id)
        REFERENCES public.competitions (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;
ALTER TABLE IF EXISTS public.team_stats DROP CONSTRAINT IF EXISTS team_stats_competition_id_fkey;

ALTER TABLE IF EXISTS public.team_stats DROP CONSTRAINT IF EXISTS team_stats_competition_id_ladder_fkey;

ALTER TABLE IF EXISTS public.team_stats DROP CONSTRAINT IF EXISTS team_stats_team_id_fkey;

ALTER TABLE IF EXISTS public.team_stats
    ADD CONSTRAINT team_stats_competition_id_fkey FOREIGN KEY (competition_id)
        REFERENCES public.competitions (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;

ALTER TABLE IF EXISTS public.team_stats
    ADD CONSTRAINT team_stats_competition_id_ladder_fkey FOREIGN KEY (competition_id, ladder)
        REFERENCES public.ladders (competition_id, ladder) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;

ALTER TABLE IF EXISTS public.team_stats
    ADD CONSTRAINT team_stats_team_id_fkey FOREIGN KEY (team_id)
        REFERENCES public.teams (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;
ALTER TABLE IF EXISTS public.team_glicko_history DROP CONSTRAINT IF EXISTS team_glicko_history_competition_id_fkey;

ALTER TABLE IF EXISTS public.team_glicko_history DROP CONSTRAINT IF EXISTS team_glicko_history_competition_id_ladder_fkey;

ALTER TABLE IF EXISTS public.team_glicko_history DROP CONSTRAINT IF EXISTS team_glicko_history_game_match_id_fkey;

ALTER TABLE IF EXISTS public.team_glicko_history DROP CONSTRAINT IF EXISTS team_glicko_history_team_id_fkey;

ALTER TABLE IF EXISTS public.team_glicko_history
    ADD CONSTRAINT team_glicko_history_competition_id_fkey FOREIGN KEY (competition_id)
        REFERENCES public.competitions (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;

ALTER TABLE IF EXISTS public.team_glicko_history
    ADD CONSTRAINT team_glicko_history_competition_id_ladder_fkey FOREIGN KEY (competition_id, ladder)
        REFERENCES public.ladders (competition_id, ladder) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;

ALTER TABLE IF EXISTS public.team_glicko_history
    ADD CONSTRAINT team_glicko_history_game_match_id_fkey FOREIGN KEY (game_match_id)
        REFERENCES public.game_matches (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;

ALTER TABLE IF EXISTS public.team_glicko_history
    ADD CONSTRAINT team_glicko_history_team_id_fkey FOREIGN KEY (team_id)
        REFERENCES public.teams (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE;

END;