-- This script was generated by the Schema Diff utility in pgAdmin 4.
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.
BEGIN;
ALTER TABLE IF EXISTS public.competitions
    ADD COLUMN settings jsonb NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.ladders
    ADD COLUMN max_queued_per_team integer NOT NULL DEFAULT 10;

END;